<?php

/**
 * Server
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jeuxsteam
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Server extends BaseServer
{
  public function getAddress()
  {
    return sprintf('%s:%d', $this->getIp(), $this->getPort());
  }
}
